### ISSUE TITLE
[Bug]: Loading template does not work

### ISSUE THREAD

**Issue by ThexXTURBOXx** [kerhub/issue-forms-creator#129]
### Description

Loading any template (also pasting from YAML) does not work for me.
See below for a MRE.

### Minimal Reproduction

I am using the following MRE:

```yml
name: Bug report
description: Create a bug report to help us improve
title: '[Bug]: '
body:
  - type: textarea
    attributes:
      label: Description
      description: Hello
      placeholder: Trying to load anything
    validations:
      required: true

```
