### ISSUE TITLE
[Bug]: checkboxes with required field are no longer valid

### ISSUE THREAD

**Issue by lrstanley** [kerhub/issue-forms-creator#20]
### Description

When generating a section with the `checkboxes` type, and selecting `required: true`, it will generate YAML that no longer correctly matches the Github issue-forms syntax.

### Minimal Reproduction

1. Go to https://issue-forms-creator.app/new
2. Create a `checkboxes` type
4. Create a new `checkbox`, and make that checkbox `required: true`.
5. Generate YAML, and try and use within Github.
6. You should receive an error stating that the YAML is not valid.

This is what gets generated, as an example:

```yaml
[...]
  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: "Please confirm the following:"
      options:
        - label: >-
            I have confirmed that someone else has not submitted a similar
            bug report.
          validations:
            required: true
```

This is what **should** be generated:

```yaml
[...]
  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: "Please confirm the following:"
      options:
        - label: >-
            I have confirmed that someone else has not submitted a similar
            bug report.
          required: true
```
